services:
  # Backend API Service
  - type: web
    name: fifufa-backend
    env: node
    region: oregon
    buildCommand: "cd fifufa-be && npm install"
    startCommand: "cd fifufa-be && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: REPLICATE_API_TOKEN
        fromService: fifufa-backend
        fromEnvVar: REPLICATE_API_TOKEN

  # Frontend Static Site
  - type: static
    name: fifufa-frontend
    env: static
    region: oregon
    buildCommand: "cd fifufa-ui && npm install && npm run build"
    staticPublishPath: "./fifufa-ui/dist"
    envVars:
      - key: VITE_API_URL
        fromService: fifufa-backend
        fromEnvVar: RENDER_EXTERNAL_URL

envVarGroups:
  - name: app-secrets
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false